name: Deploy to OpenShift

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]

    steps:
      # Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v4

      # Installer oc (si pas déjà installé sur ton PC)
      - name: Install OpenShift CLI
        run: |
          if ! command -v oc &> /dev/null
          then
            echo "Installing oc..."
            curl -LO "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/openshift-client-linux.tar.gz"
            tar xzf openshift-client-linux.tar.gz
            sudo mv oc /usr/local/bin/
          fi
          oc version

      # Login OpenShift
      - name: Login to OpenShift
        run: |
          oc login --token="${{ secrets.OPENSHIFT_TOKEN }}" --server="${{ secrets.OPENSHIFT_SERVER }}"
          oc whoami

      # Sélection du projet
      - name: Set project
        run: oc project boubacar605-dev

      # Lancer la build
      - name: Start build
        run: |
          oc start-build webapp
          echo "Build started"

      # Attendre la fin de la build
      - name: Wait for build
        run: |
          oc wait --for=condition=complete build --all -n boubacar605-dev --timeout=300s

      # Déployer
      - name: Rollout deployment
        run: |
          oc rollout latest dc/webapp -n boubacar605-dev

      # Attendre que le déploiement soit prêt
      - name: Wait for deployment
        run: |
          oc rollout status dc/webapp -n boubacar605-dev
