name: Deploy to OpenShift

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install OpenShift CLI
        run: |
          if ! command -v oc &> /dev/null
          then
            curl -LO "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/openshift-client-linux.tar.gz"
            tar xzf openshift-client-linux.tar.gz
            sudo mv oc /usr/local/bin/
          fi

      - name: Login to OpenShift
        run: |
          oc login --token="${{ secrets.OPENSHIFT_TOKEN }}" --server="${{ secrets.OPENSHIFT_SERVER }}"
          oc whoami

      - name: Set project
        run: oc project boubacar605-dev

      - name: Start build
        run: |
          oc start-build projet-3-tiers-webapp-git --follow

      - name: Restart deployment
        run: |
          oc rollout restart deployment webapp

      - name: Wait for deployment
        run: |
          oc rollout status deployment webapp --timeout=300s
